name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: HTML/CSS/JS Minifier    
        uses: docker://devatherock/minify-js:latest
        with:
          directory: '.' 
          add_suffix: false
      - name: git-ftp push
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          options: --remote-root ${{ secrets.FTP_SERVER_DIR }} --verbose

